import type { Database } from "bun:sqlite";
import { ApiError } from "../http";
import type { DefinitionMeta } from "../components/types";

const now=()=>new Date().toISOString();
type Row={id:string;name:string;head_rev:number;design_system:string;deleted_at:string|null;created_at:string;updated_at:string};
export class ComponentRepo {
  constructor(private db:Database) {}
  row(id:string,includeDeleted=false):Row { const r=this.db.query(`SELECT * FROM components WHERE id=? ${includeDeleted?"":"AND deleted_at IS NULL"}`).get(id) as Row|null; if(!r) throw new ApiError(404,"not_found","Component not found"); return r; }
  cas(id:string,baseRev:number):Row { const r=this.row(id); if(r.head_rev!==baseRev) throw new ApiError(409,"revision_conflict","Component revision has changed",{currentRev:r.head_rev}); return r; }
  create(id:string,name:string,source:string,designSystem="shadcn",message?:string) { return this.db.transaction(()=>{if(this.db.query("SELECT 1 FROM components WHERE id=? OR name=?").get(id,name)) throw new ApiError(409,"already_exists","Component id or name already exists"); const at=now(); this.db.query("INSERT INTO components (id,name,head_rev,design_system,deleted_at,created_at,updated_at) VALUES (?,?,1,?,NULL,?,?)").run(id,name,designSystem,at,at); this.db.query("INSERT INTO component_revisions (component_id,rev,source,design_system,message,created_at) VALUES (?,1,?,?,?,?)").run(id,source,designSystem,message??null,at); return {id,rev:1 as const};})(); }
  save(id:string,source:string|undefined,designSystem:string|undefined,baseRev:number,message?:string) { return this.db.transaction(()=>{const r=this.cas(id,baseRev),head=this.source(id,r.head_rev),nextSource=source??head.source,nextSystem=designSystem??r.design_system,rev=r.head_rev+1,at=now();this.db.query("INSERT INTO component_revisions (component_id,rev,source,design_system,message,created_at) VALUES (?,?,?,?,?,?)").run(id,rev,nextSource,nextSystem,message??null,at);this.db.query("UPDATE components SET head_rev=?,design_system=?,updated_at=? WHERE id=? AND deleted_at IS NULL").run(rev,nextSystem,at,id);return {rev};})(); }
  delete(id:string,baseRev:number) { this.db.transaction(()=>{this.cas(id,baseRev);this.db.query("UPDATE components SET deleted_at=?,updated_at=? WHERE id=? AND deleted_at IS NULL").run(now(),now(),id);})(); }
  list(){return (this.db.query(`SELECT c.*, (SELECT MAX(version) FROM component_publishes p WHERE p.component_id=c.id AND p.status='active') latest FROM components c WHERE deleted_at IS NULL ORDER BY updated_at DESC`).all() as (Row&{latest:number|null})[]).map(r=>({id:r.id,name:r.name,designSystem:r.design_system,headRev:r.head_rev,latestVersion:r.latest,updatedAt:r.updated_at}));}
  meta(id:string){const r=this.row(id);return {id:r.id,name:r.name,designSystem:r.design_system,headRev:r.head_rev,versions:this.versions(id),updatedAt:r.updated_at};}
  source(id:string,rev?:number){const r=this.row(id); const n=rev??r.head_rev; const x=this.db.query("SELECT rev,source,design_system,message,created_at FROM component_revisions WHERE component_id=? AND rev=?").get(id,n) as {rev:number;source:string;design_system:string;message:string|null;created_at:string}|null;if(!x)throw new ApiError(404,"not_found","Component revision not found");return {rev:x.rev,source:x.source,designSystem:x.design_system,message:x.message,createdAt:x.created_at};}
  revisions(id:string){this.row(id);return (this.db.query("SELECT rev,design_system,message,created_at FROM component_revisions WHERE component_id=? ORDER BY rev DESC").all(id) as {rev:number;design_system:string;message:string|null;created_at:string}[]).map(x=>({rev:x.rev,designSystem:x.design_system,message:x.message,createdAt:x.created_at}));}
  restore(id:string,sourceRev:number,baseRev:number){const src=this.source(id,sourceRev);return this.save(id,src.source,src.designSystem,baseRev,`Restore revision ${sourceRev}`);}
  stage(id:string,baseRev:number,artifact:{compiledJs:string;bundleHash:string;sourceHash:string;meta:DefinitionMeta},message?:string){return this.db.transaction(()=>{const r=this.cas(id,baseRev);if(this.db.query("SELECT 1 FROM component_publishes WHERE component_id=? AND rev=?").get(id,r.head_rev))throw new ApiError(409,"already_published","This revision is already published",{currentRev:r.head_rev});const max=this.db.query("SELECT MAX(version) v FROM component_publishes WHERE component_id=?").get(id) as {v:number|null};const version=(max.v??0)+1;this.db.query(`INSERT INTO component_publishes (component_id,version,rev,status,compiled_js,definition_meta,source_hash,bundle_hash,host_abi_version,message,published_at) VALUES (?,?,?,'staging',?,?,?,?,1,?,?)`).run(id,version,r.head_rev,artifact.compiledJs,JSON.stringify(artifact.meta),artifact.sourceHash,artifact.bundleHash,message??null,now());return {version,rev:r.head_rev};})();}
  activate(id:string,version:number){this.db.transaction(()=>{const x=this.db.query("UPDATE component_publishes SET status='active' WHERE component_id=? AND version=? AND status='staging'").run(id,version);if(!x.changes)throw new Error("Staging publish disappeared");})();}
  fail(id:string,version:number){this.db.query("UPDATE component_publishes SET status='failed' WHERE component_id=? AND version=? AND status='staging'").run(id,version);}
  versions(id:string){this.row(id);return (this.db.query("SELECT p.version,p.rev,p.status,p.published_at,r.design_system FROM component_publishes p JOIN component_revisions r ON r.component_id=p.component_id AND r.rev=p.rev WHERE p.component_id=? ORDER BY p.version").all(id) as {version:number;rev:number;status:string;published_at:string;design_system:string}[]).map(x=>({version:x.version,rev:x.rev,status:x.status,designSystem:x.design_system,publishedAt:x.published_at}));}
  activeBundle(id:string,version:number){const x=this.db.query("SELECT compiled_js js,bundle_hash hash FROM component_publishes WHERE component_id=? AND version=? AND status='active'").get(id,version) as {js:string;hash:string}|null;if(!x)throw new ApiError(404,"not_found","Component version not found");return x;}
  version(id:string,version:number){const x=this.db.query(`SELECT p.version,p.rev,p.definition_meta,p.bundle_hash,p.host_abi_version,p.published_at,r.source,r.design_system FROM component_publishes p JOIN component_revisions r ON r.component_id=p.component_id AND r.rev=p.rev WHERE p.component_id=? AND p.version=? AND p.status='active'`).get(id,version) as {version:number;rev:number;definition_meta:string;bundle_hash:string;host_abi_version:number;published_at:string;source:string;design_system:string}|null;if(!x)throw new ApiError(404,"not_found","Component version not found");return {version:x.version,rev:x.rev,source:x.source,designSystem:x.design_system,...JSON.parse(x.definition_meta),bundleHash:x.bundle_hash,hostAbiVersion:x.host_abi_version,publishedAt:x.published_at};}
}

export function failStagingPublishes(db:Database){return db.query("UPDATE component_publishes SET status='failed' WHERE status='staging'").run().changes;}
