export type ShimName = "react"|"react-dom"|"react-jsx-runtime"|"zod"|"json-render-react";
export const ABI_V1 = {
  "react": { sharedKey:"react", module:"react", hasDefault:true, named:["Activity","Children","Component","Fragment","Profiler","PureComponent","StrictMode","Suspense","__CLIENT_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE","__COMPILER_RUNTIME","act","cache","cacheSignal","captureOwnerStack","cloneElement","createContext","createElement","createRef","forwardRef","isValidElement","lazy","memo","startTransition","unstable_useCacheRefresh","use","useActionState","useCallback","useContext","useDebugValue","useDeferredValue","useEffect","useEffectEvent","useId","useImperativeHandle","useInsertionEffect","useLayoutEffect","useMemo","useOptimistic","useReducer","useRef","useState","useSyncExternalStore","useTransition","version"] },
  "react-dom": { sharedKey:"react-dom", module:"react-dom", hasDefault:true, named:["__DOM_INTERNALS_DO_NOT_USE_OR_WARN_USERS_THEY_CANNOT_UPGRADE","createPortal","flushSync","preconnect","prefetchDNS","preinit","preinitModule","preload","preloadModule","requestFormReset","unstable_batchedUpdates","useFormState","useFormStatus","version"] },
  "react-jsx-runtime": { sharedKey:"react-jsx-runtime", module:"react/jsx-runtime", hasDefault:true, named:["Fragment","jsx","jsxs"] },
  "zod": { sharedKey:"zod", module:"zod", hasDefault:true, named:["$brand","$input","$output","NEVER","TimePrecision","ZodAny","ZodArray","ZodBase64","ZodBase64URL","ZodBigInt","ZodBigIntFormat","ZodBoolean","ZodCIDRv4","ZodCIDRv6","ZodCUID","ZodCUID2","ZodCatch","ZodCodec","ZodCustom","ZodCustomStringFormat","ZodDate","ZodDefault","ZodDiscriminatedUnion","ZodE164","ZodEmail","ZodEmoji","ZodEnum","ZodError","ZodExactOptional","ZodFile","ZodFirstPartyTypeKind","ZodFunction","ZodGUID","ZodIPv4","ZodIPv6","ZodISODate","ZodISODateTime","ZodISODuration","ZodISOTime","ZodIntersection","ZodIssueCode","ZodJWT","ZodKSUID","ZodLazy","ZodLiteral","ZodMAC","ZodMap","ZodNaN","ZodNanoID","ZodNever","ZodNonOptional","ZodNull","ZodNullable","ZodNumber","ZodNumberFormat","ZodObject","ZodOptional","ZodPipe","ZodPrefault","ZodPreprocess","ZodPromise","ZodReadonly","ZodRealError","ZodRecord","ZodSet","ZodString","ZodStringFormat","ZodSuccess","ZodSymbol","ZodTemplateLiteral","ZodTransform","ZodTuple","ZodType","ZodULID","ZodURL","ZodUUID","ZodUndefined","ZodUnion","ZodUnknown","ZodVoid","ZodXID","ZodXor","_ZodString","_default","_function","any","array","base64","base64url","bigint","boolean","catch","check","cidrv4","cidrv6","clone","codec","coerce","config","core","cuid","cuid2","custom","date","decode","decodeAsync","describe","discriminatedUnion","e164","email","emoji","encode","encodeAsync","endsWith","enum","exactOptional","file","flattenError","float32","float64","formatError","fromJSONSchema","function","getErrorMap","globalRegistry","gt","gte","guid","hash","hex","hostname","httpUrl","includes","instanceof","int","int32","int64","intersection","invertCodec","ipv4","ipv6","iso","json","jwt","keyof","ksuid","lazy","length","literal","locales","looseObject","looseRecord","lowercase","lt","lte","mac","map","maxLength","maxSize","meta","mime","minLength","minSize","multipleOf","nan","nanoid","nativeEnum","negative","never","nonnegative","nonoptional","nonpositive","normalize","null","nullable","nullish","number","object","optional","overwrite","parse","parseAsync","partialRecord","pipe","positive","prefault","preprocess","prettifyError","promise","property","readonly","record","refine","regex","regexes","registry","safeDecode","safeDecodeAsync","safeEncode","safeEncodeAsync","safeParse","safeParseAsync","set","setErrorMap","size","slugify","startsWith","strictObject","string","stringFormat","stringbool","success","superRefine","symbol","templateLiteral","toJSONSchema","toLowerCase","toUpperCase","transform","treeifyError","trim","tuple","uint32","uint64","ulid","undefined","union","unknown","uppercase","url","util","uuid","uuidv4","uuidv6","uuidv7","void","xid","xor","z"] },
  "json-render-react": { sharedKey:"json-render-react", module:"@json-render/react", hasDefault:false, named:["ActionProvider","ConfirmDialog","JSONUIProvider","Renderer","RepeatScopeProvider","StateProvider","ValidationProvider","VisibilityProvider","buildSpecFromParts","createRenderer","createStateStore","defineRegistry","elementTreeSchema","flatToTree","getTextFromParts","schema","useAction","useActions","useBoundProp","useChatUI","useFieldValidation","useIsVisible","useJsonRenderMessage","useOptionalValidation","useRepeatScope","useStateBinding","useStateStore","useStateValue","useUIStream","useValidation","useVisibility"] },
} as const;
export function emitShim(name:ShimName):string {
  const item=ABI_V1[name];
  const lines=["const m = globalThis.__easyUiShared["+JSON.stringify(item.sharedKey)+"];" as string];
  // Aliased exports: names like `catch`/`enum`/`function` are valid IdentifierNames
  // (legal after `as`) but reserved words cannot be `const` bindings.
  item.named.forEach((key,index)=>{
    lines.push("const __b"+index+" = m["+JSON.stringify(key)+"];");
    lines.push("export { __b"+index+" as "+key+" };");
  });
  if(item.hasDefault) lines.push("export default m.default ?? m;");
  return lines.join("\n")+"\n";
}
export async function verifyShimAbi():Promise<void> {
  for(const [name,item] of Object.entries(ABI_V1)) {
    const actual=Object.keys(await import(item.module)).filter(k=>k!=="default"&&/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k)).sort();
    if(JSON.stringify(actual)!==JSON.stringify(item.named)) console.warn("Shim ABI v1 export drift for "+name);
  }
}


