import { createTestHandler } from "./test-auth";
import { afterEach, describe, expect, test } from "bun:test";
import { mkdtemp, rm } from "node:fs/promises";
import { resolve } from "node:path";
import { z } from "zod";
import { openDatabase } from "./db";
import { catalogManifest } from "./routes/components";
import { clearCustomComponentCacheForTests, loadCustomComponents } from "../src/customComponents/loader";

const dirs:string[]=[];
afterEach(async()=>{for(const dir of dirs.splice(0)) await rm(dir,{recursive:true,force:true});});
async function setup(){const dir=await mkdtemp(resolve(process.cwd(),".components-layout-test-"));dirs.push(dir);const db=openDatabase(":memory:");return {db,handler:createTestHandler(db,{dataDir:dir})};}
const request=(url:string,method="GET",body?:unknown)=>new Request(`http://test/api${url}`,{method,headers:body?{"content-type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined});
const props=`z.strictObject({gap:z.enum(["none","sm","md"]).default("md"),padding:z.enum(["none","sm","md"]).default("none"),direction:z.enum(["vertical","horizontal","none"]).default("vertical"),wrap:z.boolean().default(false)})`;
const fullLayout=`{version:1 as const,spacing:["gap","padding"] as ("gap"|"padding")[],flow:{kind:"flex" as const,direction:{prop:"direction",vertical:["vertical"],horizontal:["horizontal"],none:["none"]},wrap:{prop:"wrap",enabled:[true]},slot:"default"}}`;
function source(fields:string,render=`return <div data-gap={props.gap}>{slots.default}</div>`){return `import {z} from "zod";
export const definition={${fields}};
export default function LayoutComponent({props,slots,children}:any){if(children!==slots.default)throw new Error("children contract mismatch");${render}}`;}
const validFields=`props:${props},description:"Layout component",slots:["default"],atomicLevel:"molecule" as const,layoutNeutral:true as const,layout:${fullLayout}`;
async function rejected(fields:string,needle:string){const {db,handler}=await setup();const response=await handler(request("/components","POST",{id:`case-${crypto.randomUUID().slice(0,8)}`,name:"LayoutCase",source:source(fields)}));expect(response.status).toBe(422);expect(JSON.stringify(await response.json())).toContain(needle);db.close();}

describe("custom component layout metadata",()=>{
  test("publishes full metadata and an input props schema without false required defaults",async()=>{const {db,handler}=await setup();expect((await handler(request("/components","POST",{id:"layout-box",name:"LayoutBox",source:source(validFields)}))).status).toBe(201);const published=await handler(request("/components/layout-box/publish","POST",{baseRev:1}));expect(published.status).toBe(201);expect(await published.json()).toMatchObject({warnings:[]});const version=await (await handler(request("/components/layout-box/versions/1"))).json() as Record<string,unknown>;const manifest=catalogManifest(db)[0] as Record<string,unknown>;for(const dto of [version,manifest]){expect(dto).toMatchObject({layoutNeutral:true,layout:{version:1,spacing:["gap","padding"],flow:{kind:"flex",slot:"default"}}});const schema=dto.propsJsonSchema as {required?:string[];properties?:Record<string,unknown>};expect(schema.properties).toMatchObject({gap:expect.any(Object),padding:expect.any(Object),direction:expect.any(Object),wrap:expect.any(Object)});expect(schema.required??[]).toEqual([]);}db.close();},15000);

  const d3Cases:[string,string,string][]=[
    ["rejects layout without spacing or spacer",`props:${props},description:"x",layout:{version:1 as const}`,"requires spacing or spacer"],
    ["rejects unsupported layout versions",`props:${props},description:"x",layout:{version:2,spacing:["gap"]}`,"expected 1"],
    ["rejects duplicate spacing props",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap","gap"]}`,"spacing contains duplicates"],
    ["rejects an unknown spacing prop",`props:${props},description:"x",layout:{version:1 as const,spacing:["margin"]}`,"Invalid option"],
    ["rejects spacer combined with slots",`props:z.strictObject({}),description:"x",slots:["default"],layout:{version:1 as const,spacer:true as const}`,"spacer is incompatible"],
    ["rejects spacer combined with spacing",`props:${props},description:"x",layout:{version:1 as const,spacer:true as const,spacing:["gap"]}`,"spacer is incompatible"],
    ["rejects missing spacing props in props schema",`props:z.strictObject({}),description:"x",layout:{version:1 as const,spacing:["gap"]}`,"gap is missing from props"],
    ["rejects non-enum spacing props",`props:z.strictObject({gap:z.string()}),description:"x",layout:{version:1 as const,spacing:["gap"]}`,"enum subset"],
    ["rejects spacing values outside the canonical scale",`props:z.strictObject({gap:z.enum(["tiny","md"])}),description:"x",layout:{version:1 as const,spacing:["gap"]}`,"enum subset"],
    ["rejects flow without gap spacing",`props:${props},description:"x",layout:{version:1 as const,spacing:["padding"],flow:{kind:"flex" as const,direction:"vertical" as const}}`,"flow requires gap"],
    ["rejects non-flex flow kinds",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"grid",direction:"vertical" as const}}`,"flex"],
    ["rejects an undeclared flow slot",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:"vertical" as const,slot:"items"}}`,"slot items is not declared"],
    ["rejects a missing direction prop",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:{prop:"axis",vertical:["v"],horizontal:["h"]}}}`,"direction prop axis is missing"],
    ["rejects a missing wrap prop",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:"vertical" as const,wrap:{prop:"enabled",enabled:[true]}}}`,"wrap prop enabled is missing"],
    ["rejects the same direction and wrap prop",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:{prop:"direction",vertical:["vertical"],horizontal:["horizontal"]},wrap:{prop:"direction",enabled:["none"]}}}`,"direction and wrap props must differ"],
    ["rejects empty direction domains",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:{prop:"direction",vertical:[],horizontal:["horizontal"]}}}`,"vertical must be a non-empty array"],
    ["rejects duplicate direction domain values",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:{prop:"direction",vertical:["vertical","vertical"],horizontal:["horizontal"]}}}`,"vertical must contain unique values"],
    ["rejects overlapping direction domains",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:{prop:"direction",vertical:["vertical"],horizontal:["vertical"]}}}`,"pairwise disjoint"],
    ["rejects direction values outside their prop schema",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:{prop:"direction",vertical:["diagonal"],horizontal:["horizontal"]}}}`,"is not accepted by its prop schema"],
    ["rejects non-JSON-safe direction values",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:{prop:"direction",vertical:[undefined],horizontal:["horizontal"]}}}`,"Invalid input"],
    ["rejects empty wrap enabled domains",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:"vertical" as const,wrap:{prop:"wrap",enabled:[]}}}`,"wrap.enabled must be a non-empty array"],
    ["rejects duplicate wrap enabled values",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:"vertical" as const,wrap:{prop:"wrap",enabled:[true,true]}}}`,"wrap.enabled must contain unique values"],
    ["rejects wrap values outside their prop schema",`props:${props},description:"x",layout:{version:1 as const,spacing:["gap"],flow:{kind:"flex" as const,direction:"vertical" as const,wrap:{prop:"wrap",enabled:["yes"]}}}`,"is not accepted by its prop schema"],
  ];
  for(const [name,fields,needle] of d3Cases) test(name,()=>rejected(fields,needle));

  const d4Cases:[string,string,string][]=[
    ["requires an explicitly declared default slot",validFields.replace(`slots:["default"],`,""),"explicitly declared default slot"],
    ["requires non-empty spacing for layout-neutral components",validFields.replace(`layout:${fullLayout}`,`layout:{version:1 as const,spacer:true as const}`),"non-empty layout.spacing"],
    ["forbids events on layout-neutral components",`${validFields},events:["press"]`,"cannot declare events"],
    ["forbids typed event payloads on layout-neutral components",`${validFields},events:{press:z.object({value:z.string()})}`,"cannot declare events"],
    ["forbids interactive layout-neutral components",`${validFields},interactive:true`,"cannot be interactive"],
    ["forbids organism layout-neutral components",validFields.replace(`atomicLevel:"molecule" as const`,`atomicLevel:"organism" as const`),"must be atom or molecule"],
  ];
  for(const [name,fields,needle] of d4Cases) test(name,()=>rejected(fields,needle));

  test("rejects oversized conformanceProps on save",async()=>{await rejected(`${validFields},conformanceProps:{label:${JSON.stringify("x".repeat(17*1024))}}`,"16384-byte");});

  test("rejects required props without an example or conformanceProps on publish",async()=>{const {db,handler}=await setup();const fields=validFields.replace(`props:${props}`,`props:z.strictObject({gap:z.enum(["md"]).default("md"),padding:z.enum(["none"]).default("none"),direction:z.enum(["vertical","horizontal","none"]).default("vertical"),wrap:z.boolean().default(false),label:z.string()})`);expect((await handler(request("/components","POST",{id:"required-layout",name:"RequiredLayout",source:source(fields)}))).status).toBe(201);const response=await handler(request("/components/required-layout/publish","POST",{baseRev:1}));expect(response.status).toBe(422);expect(JSON.stringify(await response.json())).toContain("needs definition.example or server-only definition.conformanceProps");db.close();},15000);

  test("uses the parsed example when empty props do not parse",async()=>{const {db,handler}=await setup();const requiredProps=`z.strictObject({gap:z.enum(["md"]).default("md"),padding:z.enum(["none"]).default("none"),direction:z.enum(["vertical","horizontal","none"]).default("vertical"),wrap:z.boolean().default(false),label:z.string().transform(value=>value.toUpperCase())})`;const exampleSource=source(validFields.replace(`props:${props}`,`props:${requiredProps}`)+`,example:{label:"example"}`,`if(props.label!=="EXAMPLE")throw new Error("unparsed example");return <div>{slots.default}</div>`);expect((await handler(request("/components","POST",{id:"example-conformance",name:"ExampleConformance",source:exampleSource}))).status).toBe(201);expect((await handler(request("/components/example-conformance/publish","POST",{baseRev:1}))).status).toBe(201);db.close();},15000);

  test("rejects conformanceProps that do not parse and renders parsed conformance props",async()=>{const {db,handler}=await setup();const requiredProps=`z.strictObject({gap:z.enum(["md"]).default("md"),padding:z.enum(["none"]).default("none"),direction:z.enum(["vertical","horizontal","none"]).default("vertical"),wrap:z.boolean().default(false),label:z.string().transform(value=>value.toUpperCase())})`;const invalid=source(validFields.replace(`props:${props}`,`props:${requiredProps}`)+`,conformanceProps:{label:1}`);expect((await handler(request("/components","POST",{id:"invalid-conformance",name:"InvalidConformance",source:invalid}))).status).toBe(201);expect((await handler(request("/components/invalid-conformance/publish","POST",{baseRev:1}))).status).toBe(422);db.close();const next=await setup();const parsedSource=source(validFields.replace(`props:${props}`,`props:${requiredProps}`)+`,conformanceProps:{label:"parsed"}`,`if(props.label!=="PARSED")throw new Error("unparsed props");return <div>{slots.default}</div>`);expect((await next.handler(request("/components","POST",{id:"parsed-conformance",name:"ParsedConformance",source:parsedSource}))).status).toBe(201);const publish=await next.handler(request("/components/parsed-conformance/publish","POST",{baseRev:1}));if(publish.status!==201)throw new Error(await publish.text());next.db.close();},20000);

  test("rejects a layout-neutral component that swallows the sentinel",async()=>{const {db,handler}=await setup();const swallowing=source(validFields,`return <div>no children</div>`).replace(`if(children!==slots.default)throw new Error("children contract mismatch");`,"");expect((await handler(request("/components","POST",{id:"swallow-layout",name:"SwallowLayout",source:swallowing}))).status).toBe(201);const response=await handler(request("/components/swallow-layout/publish","POST",{baseRev:1}));expect(response.status).toBe(422);expect(JSON.stringify(await response.json())).toContain("must render its default slot/children");db.close();},15000);

  test("keeps conformanceProps out of metadata, client bundle, and bundle hash",async()=>{const {db,handler}=await setup();const requiredProps=`z.strictObject({gap:z.enum(["md"]).default("md"),padding:z.enum(["none"]).default("none"),direction:z.enum(["vertical","horizontal","none"]).default("vertical"),wrap:z.boolean().default(false),label:z.string()})`;const withSecret=(value:string)=>source(validFields.replace(`props:${props}`,`props:${requiredProps}`)+`,conformanceProps:{label:${JSON.stringify(value)}}`);expect((await handler(request("/components","POST",{id:"server-only",name:"ServerOnly",source:withSecret("secret-alpha")}))).status).toBe(201);const publishOne=await handler(request("/components/server-only/publish","POST",{baseRev:1}));if(publishOne.status!==201)throw new Error(await publishOne.text());const first=await (await handler(request("/components/server-only/versions/1"))).json() as {bundleHash:string;conformanceProps?:unknown};expect(first.conformanceProps).toBeUndefined();const firstBundle=await (await handler(request("/components/server-only/versions/1/bundle.js"))).text();expect(firstBundle).not.toContain("secret-alpha");expect((await handler(request("/components/server-only","PUT",{baseRev:1,source:withSecret("secret-beta")}))).status).toBe(200);const publishTwo=await handler(request("/components/server-only/publish","POST",{baseRev:2}));if(publishTwo.status!==201)throw new Error(await publishTwo.text());const second=await (await handler(request("/components/server-only/versions/2"))).json() as {bundleHash:string};expect(second.bundleHash).toBe(first.bundleHash);expect(catalogManifest(db)[0]).not.toHaveProperty("conformanceProps");db.close();},25000);

  test("loader exposes layout metadata on the client catalog definition",async()=>{clearCustomComponentCacheForTests();const layout={version:1 as const,spacing:["gap"] as ["gap"],flow:{kind:"flex" as const,direction:"vertical" as const}};const loaded=await loadCustomComponents([{id:"loader-layout",name:"LoaderLayout",version:1,bundleUrl:"/api/components/loader-layout/versions/1/bundle.js",bundleHash:"hash"}],async()=>({definition:{props:z.strictObject({gap:z.enum(["md"]).default("md")}),description:"loader",slots:["default"],layoutNeutral:true,layout},default:()=>null}));expect(loaded.definitions.LoaderLayout).toMatchObject({layoutNeutral:true,layout});});
});
