import { afterEach,describe,expect,test } from "bun:test";
import { mkdtemp,rm } from "node:fs/promises";
import { resolve } from "node:path";
import { openDatabase } from "./db";
import { createHandler } from "./main";
import { ComponentRepo,failStagingPublishes } from "./repos/components";
import { catalogManifest,publishComponent } from "./routes/components";
import { prototypeDocSchema } from "../src/prototype/schema";

const dirs:string[]=[];
afterEach(async()=>{for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
async function setup(){const dir=await mkdtemp(resolve(process.cwd(),".components-test-"));dirs.push(dir);const db=openDatabase(":memory:"),handler=createHandler(db,{dataDir:dir});return {dir,db,handler};}
const req=(url:string,method="GET",value?:unknown)=>new Request(`http://test/api${url}`,{method,headers:value?{"content-type":"application/json"}:undefined,body:value?JSON.stringify(value):undefined});
const fixture=(name:string)=>Bun.file(resolve("server/fixtures",name)).text();

describe("component API",()=>{
  test("draft checks isolate syntax, contract, console output and timeout",async()=>{const {db,handler}=await setup();
    for(const [i,file] of ["syntax-error.tsx","no-definition.tsx","props-not-zod.tsx"].entries()){const r=await handler(req("/components","POST",{id:`bad-${i}`,name:`Bad${i}`,source:await fixture(file)}));expect(r.status).toBe(422);expect((await handler(req("/health"))).status).toBe(200);}
    const logged=await handler(req("/components","POST",{id:"logs",name:"Logs",source:await fixture("console-log.tsx")}));expect(logged.status).toBe(201);
    const old=process.env.COMPONENT_EXTRACT_TIMEOUT_MS;process.env.COMPONENT_EXTRACT_TIMEOUT_MS="100";const timed=await handler(req("/components","POST",{id:"hang",name:"Hang",source:await fixture("timeout.tsx")}));if(old===undefined)delete process.env.COMPONENT_EXTRACT_TIMEOUT_MS;else process.env.COMPONENT_EXTRACT_TIMEOUT_MS=old;expect(timed.status).toBe(422);expect((await handler(req("/health"))).status).toBe(200);db.close();
  });
  test("publish emits only immutable shim imports and rejects forbidden imports",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");expect((await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source}))).status).toBe(201);const published=await handler(req("/components/rating-stars/publish","POST",{baseRev:1}));expect(published.status).toBe(201);const bundle=await handler(req("/components/rating-stars/versions/1/bundle.js"));const js=await bundle.text();expect(bundle.headers.get("cache-control")).toContain("immutable");expect(js).toContain('/api/shims/v1/react.js');expect(js).not.toMatch(/from["'](react|zod)/);const hash=new Bun.CryptoHasher("sha256").update(js).digest("hex");expect((catalogManifest(db)[0] as {bundleHash:string}).bundleHash).toBe(hash);
    for(const [i,file] of ["bare-import.tsx","css-import.tsx"].entries()){const id=`import-${i}`,name=`Import${i}`;const saved=await handler(req("/components","POST",{id,name,source:await fixture(file)}));const rejected=saved.status===422?saved:await handler(req(`/components/${id}/publish`,"POST",{baseRev:1}));expect(rejected.status).toBe(422);expect((await handler(req("/health"))).status).toBe(200);}db.close();
  });
  test("staging is invisible, failed activation stays invisible, restart fails staging",async()=>{const {db,dir}=await setup();const repo=new ComponentRepo(db),source=await fixture("rating-stars.tsx");repo.create("rating-stars","RatingStars",source);let invisible=false;const out=await publishComponent(db,repo,"rating-stars",1,dir,undefined,{afterStage:()=>{invisible=catalogManifest(db).length===0;}});expect(invisible).toBeTrue();expect(out.version).toBe(1);expect(catalogManifest(db)).toHaveLength(1);
    repo.save("rating-stars",source.replace("five-star","five star v2"),1);await expect(publishComponent(db,repo,"rating-stars",2,dir,undefined,{beforeImport:()=>{throw new Error("simulated import failure");}})).rejects.toMatchObject({status:422});expect((repo.versions("rating-stars").at(-1) as {status:string}).status).toBe("failed");
    repo.save("rating-stars",source.replace("five-star","five star v3"),2);const rev=repo.source("rating-stars");const {materializeSource,definitionMeta,sha256}=await import("./components/pipeline");const path=await materializeSource(dir,"rating-stars",rev.rev,rev.source);const mod=await import(path);repo.stage("rating-stars",3,{compiledJs:"x",bundleHash:"x",sourceHash:sha256(rev.source),meta:definitionMeta(mod.definition)});expect(failStagingPublishes(db)).toBe(1);expect((repo.versions("rating-stars").at(-1) as {status:string}).status).toBe("failed");db.close();
  });
  test("soft delete hides catalog but active bundle remains addressable",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source}));await handler(req("/components/rating-stars/publish","POST",{baseRev:1}));expect(catalogManifest(db)).toHaveLength(1);expect((await handler(req("/components/rating-stars","DELETE",{baseRev:1}))).status).toBe(204);expect(catalogManifest(db)).toHaveLength(0);expect((await handler(req("/components/rating-stars/versions/1/bundle.js"))).status).toBe(200);db.close();});
  test("prototype save pins the validated active version and later publishes do not mutate it",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source}));await handler(req("/components/rating-stars/publish","POST",{baseRev:1}));const original=prototypeDocSchema.parse(await Bun.file("prototypes/hello-world.json").json());const doc={...original,id:"rating-prototype",name:"Rating",screens:original.screens.map((s,i)=>i?s:{...s,spec:{root:"rating",elements:{rating:{type:"RatingStars",props:{value:3}}}}})};const created=await handler(req("/prototypes","POST",{doc}));expect(created.status).toBe(201);const draft1=await (await handler(req("/prototypes/rating-prototype/draft"))).json() as {components:{version:number}[];componentManifestHash:string};expect(draft1.components).toHaveLength(1);expect(draft1.components[0]!.version).toBe(1);
    await handler(req("/components/rating-stars","PUT",{baseRev:1,source:source.replace("five-star","five-star v2")}));await handler(req("/components/rating-stars/publish","POST",{baseRev:2}));const draft2=await (await handler(req("/prototypes/rating-prototype/draft"))).json() as typeof draft1;expect(draft2).toEqual(draft1);expect((db.query("SELECT component_version v FROM prototype_revision_components WHERE prototype_id='rating-prototype' AND rev=1").get() as {v:number}).v).toBe(1);db.close();});
});
