import { afterEach,describe,expect,test } from "bun:test";
import { mkdtemp,rm } from "node:fs/promises";
import { resolve } from "node:path";
import { openDatabase } from "./db";
import { createHandler } from "./main";
import { ComponentRepo,failStagingPublishes } from "./repos/components";
import { catalogManifest,publishComponent } from "./routes/components";
import { prototypeDocSchema } from "../src/prototype/schema";
import { ScreenshotService, type RunJob, type WorkerResult } from "./screenshot/service";
import { buildComponentDefinitionSchema } from "./routes/meta";
import Ajv from "ajv";

const dirs:string[]=[];
afterEach(async()=>{for(const d of dirs.splice(0))await rm(d,{recursive:true,force:true});});
async function setup(){const dir=await mkdtemp(resolve(process.cwd(),".components-test-"));dirs.push(dir);const db=openDatabase(":memory:"),handler=createHandler(db,{dataDir:dir});return {dir,db,handler};}
const req=(url:string,method="GET",value?:unknown)=>new Request(`http://test/api${url}`,{method,headers:value?{"content-type":"application/json"}:undefined,body:value?JSON.stringify(value):undefined});
const fixture=(name:string)=>Bun.file(resolve("server/fixtures",name)).text();
const neverResolves:RunJob=()=>new Promise<WorkerResult>(()=>{});
const examplesSource=(examples:string,props="z.strictObject({ value: z.number().min(0).max(5) })")=>`import { z } from "zod";
export const definition={props:${props},description:"Named examples",atomicLevel:"atom" as const,examples:${examples}};
export default function ExampleComponent({props,slots,children}:any){return <div>{JSON.stringify(props)}{String(Boolean(slots&&Object.hasOwn(slots,"default")))}{String(children===slots?.default)}</div>}`;

describe("component API",()=>{
  test("draft checks isolate syntax, contract, console output and timeout",async()=>{const {db,handler}=await setup();
    for(const [i,file] of ["syntax-error.tsx","no-definition.tsx","props-not-zod.tsx"].entries()){const r=await handler(req("/components","POST",{id:`bad-${i}`,name:`Bad${i}`,source:await fixture(file)}));expect(r.status).toBe(422);expect((await handler(req("/health"))).status).toBe(200);}
    const logged=await handler(req("/components","POST",{id:"logs",name:"Logs",source:await fixture("console-log.tsx")}));expect(logged.status).toBe(201);
    const old=process.env.COMPONENT_EXTRACT_TIMEOUT_MS;process.env.COMPONENT_EXTRACT_TIMEOUT_MS="100";const timed=await handler(req("/components","POST",{id:"hang",name:"Hang",source:await fixture("timeout.tsx")}));if(old===undefined)delete process.env.COMPONENT_EXTRACT_TIMEOUT_MS;else process.env.COMPONENT_EXTRACT_TIMEOUT_MS=old;expect(timed.status).toBe(422);expect((await handler(req("/health"))).status).toBe(200);db.close();
  });
  test("publish emits only immutable shim imports and rejects forbidden imports",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");expect((await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source}))).status).toBe(201);const published=await handler(req("/components/rating-stars/publish","POST",{baseRev:1}));expect(published.status).toBe(201);const bundle=await handler(req("/components/rating-stars/versions/1/bundle.js"));const js=await bundle.text();expect(bundle.headers.get("cache-control")).toContain("immutable");expect(js).toContain('/api/shims/v1/react.js');expect(js).not.toMatch(/from["'](react|zod)/);const hash=new Bun.CryptoHasher("sha256").update(js).digest("hex");expect((catalogManifest(db)[0] as {bundleHash:string}).bundleHash).toBe(hash);
    for(const [i,file] of ["bare-import.tsx","css-import.tsx"].entries()){const id=`import-${i}`,name=`Import${i}`;const saved=await handler(req("/components","POST",{id,name,source:await fixture(file)}));const rejected=saved.status===422?saved:await handler(req(`/components/${id}/publish`,"POST",{baseRev:1}));expect(rejected.status).toBe(422);expect((await handler(req("/health"))).status).toBe(200);}db.close();
  });
  test("round-trips atomic level and warns when it is omitted",async()=>{const {db,handler}=await setup();const baseSource=await fixture("rating-stars.tsx"),source=baseSource.replace('description: "An interactive five-star rating",','description: "An interactive five-star rating",\n  atomicLevel: "molecule" as const,');
    expect((await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source,designSystem:"wireframe"}))).status).toBe(201);const published=await handler(req("/components/rating-stars/publish","POST",{baseRev:1}));expect(await published.json()).toMatchObject({warnings:[],version:1});expect(catalogManifest(db)[0]).toMatchObject({name:"RatingStars",designSystem:"wireframe",atomicLevel:"molecule"});
    expect(await (await handler(req("/components"))).json()).toEqual([expect.objectContaining({name:"RatingStars",designSystem:"wireframe"})]);expect(await (await handler(req("/components/rating-stars"))).json()).toMatchObject({designSystem:"wireframe"});
    expect((await handler(req("/components","POST",{id:"no-level",name:"NoLevel",source:baseSource.replaceAll("RatingStars","NoLevel")}))).status).toBe(201);const noLevel=await handler(req("/components/no-level/publish","POST",{baseRev:1}));expect(await noLevel.json()).toMatchObject({warnings:[expect.stringContaining("Atomic design level")]});db.close();
  });
  test("validates design systems and builtin collisions across the registry",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");let response=await handler(req("/components","POST",{id:"bad-system",name:"BadSystem",source,designSystem:"missing"}));expect(response.status).toBe(422);expect(await response.json()).toMatchObject({error:{issues:[{path:["designSystem"]}]}});response=await handler(req("/components","POST",{id:"box",name:"Box",source}));expect(response.status).toBe(409);db.close();});
  test("catalog manifest validates and resolves the optional design-system filter",async()=>{const {db,handler}=await setup();
    expect((await handler(req("/design-systems","POST",{id:"empty-system",name:"Empty system",description:"No components"}))).status).toBe(201);
    expect(await (await handler(req("/catalog/manifest?designSystem=empty-system"))).json()).toEqual({components:[]});
    let response=await handler(req("/catalog/manifest?designSystem=missing-system"));expect(response.status).toBe(404);expect(await response.json()).toMatchObject({error:{code:"not_found"}});
    response=await handler(req("/catalog/manifest?designSystem=Bad_slug"));expect(response.status).toBe(422);expect(await response.json()).toMatchObject({error:{code:"validation_failed",issues:[{path:["designSystem"]}]}});db.close();
  });
  test("revision systems round-trip through every DTO, move, publish and restore",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx"),v2=source.replace("five-star","five-star v2");expect((await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source,designSystem:"yandex-pay"}))).status).toBe(201);
    expect(await (await handler(req("/components/rating-stars/source"))).json()).toMatchObject({rev:1,designSystem:"yandex-pay"});expect(await (await handler(req("/components/rating-stars/draft"))).json()).toMatchObject({designSystem:"yandex-pay"});expect(await (await handler(req("/components/rating-stars/revisions"))).json()).toEqual([expect.objectContaining({rev:1,designSystem:"yandex-pay"})]);
    expect((await handler(req("/components/rating-stars","PUT",{baseRev:1,source:v2}))).status).toBe(200);expect((await handler(req("/components/rating-stars/publish","POST",{baseRev:2}))).status).toBe(201);expect((await handler(req("/components/rating-stars","PUT",{baseRev:2,designSystem:"wireframe"}))).status).toBe(200);expect((await handler(req("/components/rating-stars/publish","POST",{baseRev:3}))).status).toBe(201);
    const meta=await (await handler(req("/components/rating-stars"))).json() as {designSystem:string;versions:{version:number;designSystem:string}[]};expect(meta).toMatchObject({designSystem:"wireframe",versions:[{version:1,designSystem:"yandex-pay"},{version:2,designSystem:"wireframe"}]});expect(await (await handler(req("/components/rating-stars/versions/1"))).json()).toMatchObject({rev:2,source:v2,designSystem:"yandex-pay"});expect(catalogManifest(db).map(x=>({system:x.designSystem,version:x.version}))).toEqual([{system:"wireframe",version:2},{system:"yandex-pay",version:1}]);
    expect(catalogManifest(db,"wireframe").map(x=>({system:x.designSystem,version:x.version}))).toEqual([{system:"wireframe",version:2}]);expect(catalogManifest(db,"yandex-pay").map(x=>({system:x.designSystem,version:x.version}))).toEqual([{system:"yandex-pay",version:1}]);
    expect(await (await handler(req("/catalog/manifest?designSystem=wireframe"))).json()).toMatchObject({components:[{id:"rating-stars",designSystem:"wireframe",version:2}]});expect(await (await handler(req("/catalog/manifest?designSystem=yandex-pay"))).json()).toMatchObject({components:[{id:"rating-stars",designSystem:"yandex-pay",version:1}]});expect((await (await handler(req("/catalog/manifest"))).json() as {components:unknown[]}).components).toHaveLength(2);
    db.run("UPDATE components SET design_system='yandex-pay' WHERE id='rating-stars'");expect(await (await handler(req("/components/rating-stars/versions/2"))).json()).toMatchObject({designSystem:"wireframe"});db.run("UPDATE components SET design_system='wireframe' WHERE id='rating-stars'");expect((await handler(req("/components/rating-stars/restore","POST",{rev:1,baseRev:3}))).status).toBe(200);expect(await (await handler(req("/components/rating-stars"))).json()).toMatchObject({headRev:4,designSystem:"yandex-pay"});expect(await (await handler(req("/components/rating-stars/revisions/1"))).json()).toMatchObject({source,designSystem:"yandex-pay"});
    const rows=db.query("SELECT rev,design_system FROM component_revisions WHERE component_id=? ORDER BY rev").all("rating-stars");expect(rows).toEqual([{rev:1,design_system:"yandex-pay"},{rev:2,design_system:"yandex-pay"},{rev:3,design_system:"wireframe"},{rev:4,design_system:"yandex-pay"}]);db.close();
  });
  test("PUT rejects invalid and unchanged moves",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source,designSystem:"yandex-pay"}));for(const value of [{baseRev:1},{baseRev:1,designSystem:"yandex-pay"},{baseRev:1,source}]){const response=await handler(req("/components/rating-stars","PUT",value));expect(response.status).toBe(400);expect(await response.json()).toMatchObject({error:{code:"invalid_request"}});}const unknown=await handler(req("/components/rating-stars","PUT",{baseRev:1,designSystem:"missing"}));expect(unknown.status).toBe(422);expect(await unknown.json()).toMatchObject({error:{issues:[{path:["designSystem"]}]}});db.close();});
  test("concurrent saves preserve revision and publish join invariants",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source,designSystem:"yandex-pay"}));const [move,save]=await Promise.all([handler(req("/components/rating-stars","PUT",{baseRev:1,designSystem:"wireframe"})),handler(req("/components/rating-stars","PUT",{baseRev:1,source:source.replace("five-star","concurrent save")}))]);expect([move.status,save.status].sort()).toEqual([200,409]);const head=db.query(`SELECT c.head_rev,r.source,r.design_system FROM components c JOIN component_revisions r ON r.component_id=c.id AND r.rev=c.head_rev WHERE c.id='rating-stars'`).get() as {head_rev:number;source:string;design_system:string};expect(head.head_rev).toBe(2);expect([{source,design_system:"wireframe"},{source:source.replace("five-star","concurrent save"),design_system:"yandex-pay"}]).toContainEqual({source:head.source,design_system:head.design_system});expect((await handler(req("/components/rating-stars/publish","POST",{baseRev:2}))).status).toBe(201);expect(db.query(`SELECT p.rev,r.design_system FROM component_publishes p JOIN component_revisions r ON r.component_id=p.component_id AND r.rev=p.rev WHERE p.component_id='rating-stars'`).get()).toEqual({rev:2,design_system:head.design_system});db.close();});
  test("staging is invisible, failed activation stays invisible, restart fails staging",async()=>{const {db,dir}=await setup();const repo=new ComponentRepo(db),source=await fixture("rating-stars.tsx");repo.create("rating-stars","RatingStars",source);let invisible=false;const out=await publishComponent(db,repo,"rating-stars",1,dir,undefined,{afterStage:()=>{invisible=catalogManifest(db).length===0;}});expect(invisible).toBeTrue();expect(out.version).toBe(1);expect(catalogManifest(db)).toHaveLength(1);
    repo.save("rating-stars",source.replace("five-star","five star v2"),"wireframe",1);await expect(publishComponent(db,repo,"rating-stars",2,dir,undefined,{beforeImport:()=>{throw new Error("simulated import failure");}})).rejects.toMatchObject({status:422});expect((repo.versions("rating-stars").at(-1) as {status:string}).status).toBe("failed");expect(catalogManifest(db).map(x=>x.designSystem)).toEqual(["shadcn"]);
    repo.save("rating-stars",source.replace("five-star","five star v3"),"yandex-pay",2);const rev=repo.source("rating-stars");const {materializeSource,definitionMeta,sha256}=await import("./components/pipeline");const path=await materializeSource(dir,"rating-stars",rev.rev,rev.source);const mod=await import(path);repo.stage("rating-stars",3,{compiledJs:"x",bundleHash:"x",sourceHash:sha256(rev.source),meta:definitionMeta(mod.definition)});expect(catalogManifest(db).map(x=>x.designSystem)).toEqual(["shadcn"]);expect(failStagingPublishes(db)).toBe(1);expect((repo.versions("rating-stars").at(-1) as {status:string}).status).toBe("failed");expect(catalogManifest(db).map(x=>x.designSystem)).toEqual(["shadcn"]);db.close();
  });
  test("soft delete hides new catalog entries but old pins and bundles remain readable",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source}));await handler(req("/components/rating-stars/publish","POST",{baseRev:1}));const original=prototypeDocSchema.parse(await Bun.file("prototypes/hello-world.json").json()),withRating={...original,id:"pinned-rating",name:"Pinned rating",screens:original.screens.map((s,i)=>i?s:{...s,spec:{root:"rating",elements:{rating:{type:"RatingStars",props:{value:3}}}}})};expect((await handler(req("/prototypes","POST",{doc:withRating}))).status).toBe(201);expect(catalogManifest(db)).toHaveLength(1);expect((await handler(req("/components/rating-stars","DELETE",{baseRev:1}))).status).toBe(204);expect(catalogManifest(db)).toHaveLength(0);expect(await (await handler(req("/prototypes/pinned-rating/draft"))).json()).toMatchObject({components:[{id:"rating-stars",version:1}]});expect((await handler(req("/components/rating-stars/versions/1/bundle.js"))).status).toBe(200);expect((await handler(req("/prototypes","POST",{doc:{...withRating,id:"new-rating",name:"New rating"}}))).status).toBe(422);db.close();});
  test("prototype save pins the validated active version and later publishes do not mutate it",async()=>{const {db,handler}=await setup();const source=await fixture("rating-stars.tsx");await handler(req("/components","POST",{id:"rating-stars",name:"RatingStars",source}));await handler(req("/components/rating-stars/publish","POST",{baseRev:1}));const original=prototypeDocSchema.parse(await Bun.file("prototypes/hello-world.json").json());const doc={...original,id:"rating-prototype",name:"Rating",screens:original.screens.map((s,i)=>i?s:{...s,spec:{root:"rating",elements:{rating:{type:"RatingStars",props:{value:3}}}}})};const created=await handler(req("/prototypes","POST",{doc}));expect(created.status).toBe(201);const draft1=await (await handler(req("/prototypes/rating-prototype/draft"))).json() as {components:{version:number}[];componentManifestHash:string};expect(draft1.components).toHaveLength(1);expect(draft1.components[0]!.version).toBe(1);
    await handler(req("/components/rating-stars","PUT",{baseRev:1,source:source.replace("five-star","five-star v2")}));await handler(req("/components/rating-stars/publish","POST",{baseRev:2}));const draft2=await (await handler(req("/prototypes/rating-prototype/draft"))).json() as typeof draft1;expect(draft2).toEqual(draft1);expect((db.query("SELECT component_version v FROM prototype_revision_components WHERE prototype_id='rating-prototype' AND rev=1").get() as {v:number}).v).toBe(1);db.close();});

  test("named examples publish to version DTO and manifest as sorted validated inputs",async()=>{const {db,handler}=await setup();const source=examplesSource('{zebra:{label:"last"},alpha:{label:"first"}}','z.strictObject({label:z.string().transform(value=>value.toUpperCase()),count:z.number().default(7)})');expect((await handler(req("/components","POST",{id:"named-examples",name:"NamedExamples",source}))).status).toBe(201);const published=await handler(req("/components/named-examples/publish","POST",{baseRev:1}));expect(published.status).toBe(201);expect(await published.json()).toMatchObject({hostAbiVersion:1,warnings:[]});const expected={alpha:{label:"first"},zebra:{label:"last"}};expect(await (await handler(req("/components/named-examples/versions/1"))).json()).toMatchObject({examples:expected,hostAbiVersion:1});expect(catalogManifest(db)[0]).toMatchObject({examples:expected,hostAbiVersion:1});expect(Object.keys((catalogManifest(db)[0] as {examples:Record<string,unknown>}).examples)).toEqual(["alpha","zebra"]);db.close();});

  test("named examples reject invalid names, reserved default, count and byte limits",async()=>{const padded=(count:number,size:number)=>`{${Array.from({length:count},(_,i)=>`e${i}:{value:1,padding:${JSON.stringify("x".repeat(size))}}`).join(",")}}`;for(const [index,[examples,props]] of ([['{"Bad Name":{value:1}}',undefined],['{default:{value:1}}',undefined],[`{${Array.from({length:9},(_,i)=>`e${i}:{value:1}`).join(",")}}`,undefined],[padded(1,16*1024),'z.strictObject({value:z.number(),padding:z.string()})'],[padded(5,14*1024),'z.strictObject({value:z.number(),padding:z.string()})']] as const).entries()){const {db,handler}=await setup();const response=await handler(req("/components","POST",{id:`invalid-example-${index}`,name:`InvalidExample${index}`,source:examplesSource(examples,props)}));expect(response.status).toBe(422);db.close();}});

  test("named examples identify props-schema failures and reserved nested keys",async()=>{for(const [index,[examples,needle]] of ([['{broken:{value:"no"}}','broken'],['{unsafe:{config:{$state:"/secret"}}}','unsafe']] as const).entries()){const {db,handler}=await setup();const source=examplesSource(examples,index===1?'z.strictObject({config:z.unknown()})':undefined);const response=await handler(req("/components","POST",{id:`unsafe-example-${index}`,name:`UnsafeExample${index}`,source}));expect(response.status).toBe(422);expect(JSON.stringify(await response.json())).toContain(needle);db.close();}});

  test("smoke host supports named slots and ABI2 runtime imports for every named example",async()=>{const cases=[{id:"slot-smoke",name:"SlotSmoke",source:`import {z} from "zod";import type {ReactNode} from "react";import type {EasyUIComponentProps} from "easy-ui/runtime";export const definition={props:z.strictObject({value:z.number()}),description:"slots",atomicLevel:"atom" as const,capabilities:{namedSlots:true} as const,slots:["header","items"],examples:{one:{value:1}}};export default function SlotSmoke(host:EasyUIComponentProps<{value:number}>&{children?:ReactNode}){if(!Object.hasOwn(host.slots,"default")||!Object.hasOwn(host.slots,"header")||!Object.hasOwn(host.slots,"items")||host.children!==host.slots.default)throw new Error("bad slots host");return <div/>}`},{id:"runtime-smoke",name:"RuntimeSmoke",source:`import {z} from "zod";import {token} from "easy-ui/runtime";import type {EasyUIComponentProps} from "easy-ui/runtime";export const definition={props:z.strictObject({}),description:"runtime",atomicLevel:"atom" as const,examples:{one:{}}};export default function RuntimeSmoke(host:EasyUIComponentProps<Record<string,never>>){if(!Object.hasOwn(host.slots,"default"))throw new Error("missing default slot");return <div>{token("color.brand")}</div>}`}];for(const item of cases){const {db,handler}=await setup();expect((await handler(req("/components","POST",item))).status).toBe(201);const response=await handler(req(`/components/${item.id}/publish`,"POST",{baseRev:1}));expect(response.status).toBe(201);const body=await response.json() as {warnings:string[];hostAbiVersion:number};expect(body.warnings).toEqual([]);expect(body.hostAbiVersion).toBe(2);db.close();}});

  test("component screenshot resolves exampleName and rejects unknown, absent, and props conflicts",async()=>{const {db,dir,handler:base}=await setup();expect((await base(req("/components","POST",{id:"shot-examples",name:"ShotExamples",source:examplesSource('{compact:{value:2}}')}))).status).toBe(201);expect((await base(req("/components/shot-examples/publish","POST",{baseRev:1}))).status).toBe(201);expect((await base(req("/components","POST",{id:"shot-plain",name:"ShotPlain",source:await fixture("rating-stars.tsx")}))).status).toBe(201);expect((await base(req("/components/shot-plain/publish","POST",{baseRev:1}))).status).toBe(201);const service=new ScreenshotService({db,dataDir:dir,serveDist:"dist",captureOrigin:"http://127.0.0.1:8787",chromiumAvailable:true,runJob:neverResolves});const handler=createHandler(db,{dataDir:dir,screenshots:service});const valid=await handler(req("/components/shot-examples/versions/1/screenshot","POST",{exampleName:"compact",viewport:{width:320,height:480}}));expect(valid.status).toBe(202);const {jobId}=await valid.json() as {jobId:string};expect(service.peek(jobId)?.props).toEqual({value:2});for(const [url,body,status,code] of [["/components/shot-examples/versions/1/screenshot",{exampleName:"missing",viewport:{width:320,height:480}},422,"unknown_example"],["/components/shot-plain/versions/1/screenshot",{exampleName:"missing",viewport:{width:320,height:480}},422,"unknown_example"],["/components/shot-examples/versions/1/screenshot",{exampleName:"compact",props:{value:1},viewport:{width:320,height:480}},400,"invalid_request"]] as const){const response=await handler(req(url,"POST",body));expect(response.status).toBe(status);expect(await response.json()).toMatchObject({error:{code}});}db.close();});

  test("generated component definition schema rejects invalid example maps",()=>{const {$schema:_ignored,...schema}=buildComponentDefinitionSchema();void _ignored;const validate=new Ajv({schemaId:"auto"}).compile(schema);const base={props:{},description:"x"};expect(validate({...base,examples:{valid:{}}})).toBeTrue();for(const examples of [{"Bad Name":{}},{default:{}},Object.fromEntries(Array.from({length:9},(_,i)=>[`e${i}`,{}]))])expect(validate({...base,examples})).toBeFalse();});
});
