import {afterEach,describe,expect,test} from "bun:test";
import {mkdtemp,rm} from "node:fs/promises";
import {resolve} from "node:path";
import pngjs from "pngjs";
import {openDatabase} from "./db";
import {createHandler} from "./main";
import {prototypeDocSchema,type PrototypeDoc} from "../src/prototype/schema";
import {AssetRepo} from "./repos/assets";
import {PrototypeRepo} from "./repos/prototypes";
import {VisualBaselineRepo,type BaselineMemberInput} from "./visual/baselines";

const {PNG}=pngjs; const dirs:string[]=[];
afterEach(async()=>{for(const dir of dirs.splice(0)) await rm(dir,{recursive:true,force:true});});
const request=(path:string,method="GET",body?:unknown,headers?:HeadersInit)=>new Request(`http://test/api${path}`,{method,headers:body===undefined?headers:{"content-type":"application/json",...headers},body:body===undefined?undefined:JSON.stringify(body)});
function png():Uint8Array {const image=new PNG({width:4,height:4}); image.data.fill(255); return new Uint8Array(PNG.sync.write(image));}
async function doc(id:string,screens=1):Promise<PrototypeDoc>{const base=prototypeDocSchema.parse(await Bun.file("prototypes/hello-world.json").json()); const first=base.screens[0]!; const copies=Array.from({length:screens},(_,i)=>{const screen=structuredClone(first);screen.id=i===0?"welcome":`screen-${i}`;screen.name=`Screen ${i}`;for(const element of Object.values(screen.spec.elements)) delete element.on;return screen;});return {...base,id,name:id,startScreen:"welcome",screens:copies};}
async function setup(id="baseline",screens=1){const dir=await mkdtemp(resolve(process.cwd(),".visual-baseline-test-"));dirs.push(dir);const db=openDatabase(":memory:");const handler=createHandler(db,{dataDir:dir});expect((await handler(request("/prototypes","POST",{doc:await doc(id,screens)}))).status).toBe(201);const draft=await (await handler(request(`/prototypes/${id}/draft`))).json() as {prototypeInstanceId:string;doc:PrototypeDoc};const asset=(await new AssetRepo(db,dir).ingest(png(),"image/png")).asset;return{dir,db,handler,draft,asset};}
const member=(screenId:string,assetId:string,patch:Partial<BaselineMemberInput>={}):BaselineMemberInput=>({screenId,viewport:{width:390,height:844},deviceScaleFactor:1,theme:"light",assetId,...patch});
type ErrorEnvelope={error:{code:string;currentGeneration?:number|null}};
type SetResponse={generation:number;members:{screenId:string;referenceId:string}[]};

describe("visual baseline sets",()=>{
  test("commits, reads and normalizes a complete generation",async()=>{const {handler,draft,asset}=await setup("ordered",2);const ids=draft.doc.screens.map(s=>s.id);const put=await handler(request("/visual-baselines/prototypes/ordered","PUT",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members:[member(ids[1]!,asset.id),member(ids[0]!,asset.id)]}));expect(put.status).toBe(200);const body=await put.json() as {generation:number;members:{screenId:string;referenceId:string}[]};expect(body.generation).toBe(1);expect(body.members.map(x=>x.screenId)).toEqual([...ids].sort());const get=await handler(request("/visual-baselines/prototypes/ordered"));expect(get.status).toBe(200);expect(await get.json()).toMatchObject({generation:1,rev:1,prototypeInstanceId:draft.prototypeInstanceId,members:body.members});});

  test("distinguishes missing prototype/baseline and rejects incomplete, duplicate and invalid viewports",async()=>{const {handler,draft,asset}=await setup("invalid",2);expect((await handler(request("/visual-baselines/prototypes/missing"))).status).toBe(404);const none=await handler(request("/visual-baselines/prototypes/invalid"));expect((await none.json() as ErrorEnvelope).error.code).toBe("baseline_not_found");const ids=draft.doc.screens.map(s=>s.id);for(const members of [[],[member(ids[0]!,asset.id)],[member(ids[0]!,asset.id),member(ids[0]!,asset.id)]]){const res=await handler(request("/visual-baselines/prototypes/invalid","PUT",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members}));expect((await res.json() as ErrorEnvelope).error.code).toBe("incomplete_baseline");}const bad=await handler(request("/visual-baselines/prototypes/invalid","PUT",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members:ids.map(id=>member(id,asset.id,{viewport:{width:2000,height:4000},deviceScaleFactor:2}))}));expect((await bad.json() as ErrorEnvelope).error.code).toBe("invalid_viewport");});

  test("CAS rejects stale generation and stale instance after delete/recreate",async()=>{const {db,handler,draft,asset}=await setup("cas");const payload={rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members:[member("welcome",asset.id)]};expect((await handler(request("/visual-baselines/prototypes/cas","PUT",payload))).status).toBe(200);const stale=await handler(request("/visual-baselines/prototypes/cas","PUT",payload));expect(await stale.json()).toMatchObject({error:{code:"generation_conflict",currentGeneration:1}});new PrototypeRepo(db).delete("cas",1);new PrototypeRepo(db).create(await doc("cas"));const recreated=await handler(request("/visual-baselines/prototypes/cas","PUT",payload));expect((await recreated.json() as ErrorEnvelope).error.code).toBe("instance_conflict");});

  test("rebaseline revives overlapping references, tombstones removed surfaces and preserves runs",async()=>{const {db,handler,draft,asset}=await setup("revive",2);const ids=draft.doc.screens.map(s=>s.id);const first=await (await handler(request("/visual-baselines/prototypes/revive","PUT",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members:ids.map(id=>member(id,asset.id))}))).json() as SetResponse;const removed=first.members.find(x=>x.screenId===ids[1])!;db.run("INSERT INTO visual_runs (id,reference_id,reference_asset_id,status,created_at) VALUES ('run-history',?,?, 'pass','now')",[removed.referenceId,asset.id]);const second=await (await handler(request("/visual-baselines/prototypes/revive","PUT",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:1,members:[member(ids[0]!,asset.id),member(ids[1]!,asset.id,{theme:"dark"})]}))).json() as SetResponse;expect(second.generation).toBe(2);expect(db.query("SELECT deleted_at FROM visual_references WHERE id=?").get(second.members.find(x=>x.screenId===ids[0])!.referenceId)).toEqual({deleted_at:null});expect(db.query("SELECT deleted_at IS NOT NULL deleted FROM visual_references WHERE id=?").get(removed.referenceId)).toEqual({deleted:1});expect(db.query("SELECT COUNT(*) count FROM visual_runs WHERE id='run-history'").get()).toEqual({count:1});});

  test("generic mutations cannot alter a managed reference and repo delete cleans all generations",async()=>{const {db,handler,draft,asset}=await setup("managed");const set=await (await handler(request("/visual-baselines/prototypes/managed","PUT",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members:[member("welcome",asset.id)]}))).json() as SetResponse;const referenceId=set.members[0]!.referenceId;expect((await handler(request(`/visual-references/${referenceId}`,"DELETE"))).status).toBe(409);const row=db.query("SELECT fingerprint_json FROM visual_references WHERE id=?").get(referenceId) as {fingerprint_json:string};const fp=JSON.parse(row.fingerprint_json) as unknown;expect((await handler(request("/visual-references","PUT",{fingerprint:fp,assetId:asset.id}))).status).toBe(409);new PrototypeRepo(db).delete("managed",1);expect(db.query("SELECT COUNT(*) count FROM visual_baseline_sets WHERE prototype_id='managed'").get()).toEqual({count:0});expect(db.query("SELECT deleted_at IS NOT NULL deleted FROM visual_references WHERE id=?").get(referenceId)).toEqual({deleted:1});});

  test("rolls back an injected failure after tombstoning",async()=>{const {db,dir,draft,asset}=await setup("rollback");const repo=new VisualBaselineRepo(db,dir);const first=repo.commit("rollback",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members:[member("welcome",asset.id)]});expect(()=>repo.commit("rollback",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:1,members:[member("welcome",asset.id)]},()=>{throw new Error("injected");})).toThrow("injected");expect(repo.get("rollback").generation).toBe(1);expect(db.query("SELECT deleted_at FROM visual_references WHERE id=?").get(first.members[0]!.referenceId)).toEqual({deleted_at:null});});

  test("baseline endpoints require BasicAuth and reject share/capture credentials",async()=>{const {db,dir,draft,asset}=await setup("auth");const handler=createHandler(db,{dataDir:dir,basicAuth:"user:pass"});const auth={authorization:`Basic ${Buffer.from("user:pass").toString("base64")}`};expect((await handler(request("/visual-baselines/prototypes/auth","GET",undefined,auth))).status).toBe(404);expect((await handler(request("/visual-baselines/prototypes/auth","PUT",{rev:1,prototypeInstanceId:draft.prototypeInstanceId,baseGeneration:null,members:[member("welcome",asset.id)]},auth))).status).toBe(200);expect((await handler(request("/visual-baselines/prototypes/auth","GET",undefined,{cookie:"eui_share=fake"}))).status).toBe(401);expect((await handler(request("/visual-baselines/prototypes/auth","GET",undefined,{"x-easyui-capture":"fake"}))).status).toBe(401);});
});
