// Строки Asset Workbench (волна 7.4, фидбэк §9). Технические термины MIME, sha256,
// SVG и идентификаторы `asset_…` не переводятся.

import { pluralRu } from "./common";

export const assetsStrings = {
  navLabel: "Ассеты",
  title: "Ассеты",
  subtitle: "Все загруженные файлы с фактическими размерами, прозрачностью и графом использования. Идентификатор — это sha256 содержимого, поэтому опознавать ассет удобнее по имени и по тому, где он закреплён.",
  filtersAria: "Фильтры ассетов",
  searchLabel: "Поиск по id или имени файла",
  searchPlaceholder: "префикс id или имя файла",
  mimeAll: "Все типы",
  mimeFacetsAria: "Фильтр по MIME",
  unusedOnly: "Только неиспользуемые",
  loading: "Загружаем ассеты…",
  unavailable: "Ассеты недоступны.",
  retry: "Повторить",
  emptyTitle: "Ассетов пока нет",
  empty: "Они появляются при загрузке файлов в редакторе прототипа и при публикации компонентов.",
  emptyFiltered: "Под фильтры не подошёл ни один ассет.",
  truncated: (shown: number) => `Показаны первые ${shown} ${pluralRu(shown, ["ассет", "ассета", "ассетов"])} — на сервере есть ещё. Сводки ниже посчитаны по этому срезу.`,
  gridAria: "Сетка ассетов",
  visibilityNote: "Сервер отдаёт только доступные вам ассеты: закреплённые в ваших и опубликованных прототипах и в компонентах. Ассеты, ни к чему не привязанные, видит лишь администратор — поэтому фильтр «только неиспользуемые» у обычного пользователя обычно пуст.",
  countSummary: (shown: number, total: number) => `${shown} из ${total} ${pluralRu(total, ["ассета", "ассетов", "ассетов"])}`,

  previewAlt: (name: string) => `Превью ассета ${name}`,
  previewUnavailable: "Не изображение",
  previewFailed: "Превью не загрузилось",

  copyId: "Копировать id",
  copied: "Скопировано",
  copyFailed: "Не удалось скопировать",
  fullId: "Полный id",

  metaMime: "MIME",
  metaSize: "Размер файла",
  metaServerDimensions: "Размеры (сервер)",
  metaClientDimensions: "Размеры (naturalWidth × naturalHeight)",
  metaCreatedAt: "Загружен",
  metaOriginalName: "Исходное имя",
  metaNoName: "имя не сохранено",
  dimensionsUnknown: "не определены",
  alphaLabel: "Прозрачность",
  alphaAlpha: "есть прозрачные пиксели",
  alphaOpaque: "непрозрачный",
  alphaUnknown: "не определена",
  alphaHint: "Прозрачность определяется семплированием canvas в браузере; при недоступном canvas показывается «не определена».",
  measuring: "измеряем…",

  usageTitle: "Где закреплён",
  usageLoading: "Загружаем граф использования…",
  usageUnavailable: "Граф использования недоступен.",
  usageNone: "Ассет не закреплён нигде — его ничто не удерживает.",
  usageUnusedBadge: "не используется",
  usagePrototypes: "Прототипы",
  usageComponents: "Компоненты",
  usageVisualReferences: "Эталоны",
  usageVisualRuns: "Прогоны",
  usagePinnedAtHead: "закреплён в head",
  usagePinnedHistorical: "только в старых ревизиях",
  usageRevisions: (count: number) => `${count} ${pluralRu(count, ["ревизия", "ревизии", "ревизий"])}`,
  usageVersions: (versions: number[]) => `версии ${versions.map((version) => `v${version}`).join(", ")}`,
  usageReferenceDeleted: "удалён",
  usageRunRole: { reference: "эталон", candidate: "кандидат", diff: "дифф" } as Record<string, string>,

  selectAsset: "Выберите ассет, чтобы увидеть его метаданные и граф использования.",
  detailsAria: "Карточка ассета",

  heuristicBadge: "эвристика",
  exactBadge: "точно",
  duplicatesTitle: "Одинаковые файлы",
  duplicatesExactNote: "Точные дубликаты невозможны: ассеты адресуются по sha256 содержимого, поэтому одинаковые байты — это всегда один и тот же id. Повторная загрузка того же файла возвращает существующий ассет.",
  duplicatesHeuristicTitle: "Кандидаты «тот же файл под другим id»",
  duplicatesHeuristicNote: "Эвристика по совпадающей основе имени файла: так выглядит повторная загрузка пережатого или подправленного файла. API не даёт ничего сильнее — перцептивный хеш в этой волне намеренно не делался, поэтому совпадение содержимого здесь не доказано.",
  duplicatesNone: "Кандидатов с совпадающими именами нет.",
  duplicatesGroup: (count: number) => `${count} ${pluralRu(count, ["ассет", "ассета", "ассетов"])}`,

  rasterOverSvgTitle: "Растр при живом SVG",
  rasterOverSvgNote: "Эвристика по имени: рядом с растровым файлом лежит SVG с той же основой имени — вероятно, растр стоит заменить на векторный.",
  rasterOverSvgNone: "Растров, дублирующих SVG по имени, не нашлось.",
  rasterOverSvgBadge: "есть SVG с таким же именем",
  rasterOverSvgFor: (key: string) => `Основа имени «${key}»`,
} as const;
