import type { ComponentStatus } from "../../api/client";

export const componentStatusLabels: Record<ComponentStatus, string> = {
  staging: "Подготовка",
  active: "Активна",
  failed: "Сборка не удалась",
  rejected: "Отклонена",
  deprecated: "Устарела",
  superseded: "Заменена новой",
  archived: "В архиве",
};

export const componentPage = {
  title: "Страница компонента",
  loadingMeta: "Загружаем компонент…",
  metaError: "Не удалось загрузить компонент.",
  componentNotFound: "Компонент не найден.",
  invalidAddress: "Некорректный адрес компонента.",
  loadingVersion: "Загружаем выбранную версию…",
  versionError: "Не удалось загрузить версию.",
  versionNotFound: "Версия компонента не найдена.",
  retry: "Повторить",
  noRenderableVersions: "Нет исполняемых версий",
  noRenderableVersionsBody: "У компонента нет active, deprecated или superseded-версий. Выберите версию, чтобы посмотреть документацию и код.",
  versionsTitle: "Версии компонента",
  versionSelector: "Версия",
  statusAnnouncement: (version: number, status: string) => `Выбрана версия ${version}: ${status}`,
  tabs: ["Компонент", "Документация", "Код"] as const,
  previewTitle: "Превью",
  controlsTitle: "Props",
  backgroundTitle: "Фон превью",
  lightBackground: "Светлый",
  darkBackground: "Тёмный",
  loadingBundle: "Загружаем исполняемый компонент…",
  bundleError: "Не удалось загрузить исполняемый компонент.",
  reloadRequired: "Повторная загрузка в SPA не помогла. Перезагрузите страницу целиком.",
  reloadPage: "Перезагрузить страницу",
  loadingTheme: "Загружаем тему дизайн-системы…",
  themeError: "Не удалось загрузить тему. Документация и код остаются доступны.",
  executionForbidden: "Исполнение запрещено статусом версии",
  executionForbiddenBody: (status: string) => `Версия имеет статус «${status}». Бандл не загружается.`,
  requiredProps: "Заполните обязательные props",
  previewCrashed: "Компонент завершился с ошибкой. Исправьте props, чтобы восстановить превью.",
  presetsTitle: "Пресеты",
  defaultPreset: "default",
  invalidPreset: "Пресет не проходит схему props этой версии",
  placeholder: (slot: string) => `Слот: ${slot}`,
  runtimeError: "Во время исполнения компонента произошла ошибка.",
  exportVersion: "Экспорт",
  exporting: "Экспортируем…",
  exportError: "Не удалось экспортировать версию.",
} as const;

