// Строки редактора прототипов (W0-5).

/** document.title редактора черновика (W0-3). */
export const editorDocumentTitle = (docName: string) => `${docName} · Редактор`;

export const editor = {
  dirtyAria: "Есть несохранённые изменения",
  saving: "Сохранение…",
  notSaved: "Не сохранено",
  saved: "Сохранено",
  save: "Сохранить",
  publish: "Опубликовать",
  publishing: "Публикация…",
  publishedVersion: (version: number) => `v ${version} опубликована`,
  publishDialogAria: "Публикация прототипа",
  publishDialogTitle: "Опубликовать текущую версию",
  publishDialogBody: "Опубликованную версию можно открыть по постоянной ссылке в плеере.",
  publishMessageLabel: "Сообщение к версии (необязательно)",
  publishMessagePlaceholder: "Что изменилось в этой версии",
  publishConfirm: "Опубликовать",
  saveAndPublish: "Сохранить и опубликовать",
  publishCancel: "Отменить",
  alreadyPublished: (version: number) => `Текущая ревизия уже опубликована как версия v ${version}.`,
  fixIssues: "Исправьте ошибки:",
  undo: "Отменить",
  redo: "Вернуть",
  undoTitle: "Отменить правку (Ctrl+Z / Cmd+Z)",
  redoTitle: "Вернуть правку (Ctrl+Shift+Z / Cmd+Shift+Z)",
  history: "История",
  historyPanelAria: "История прототипа",
  historyLoading: "Загружаем историю…",
  historyLoadFailed: "Не удалось загрузить историю.",
  draftRevisionsTitle: "Ревизии черновика",
  publishedVersionsTitle: "Опубликованные версии",
  revisionLabel: (rev: number) => `Ревизия ${rev}`,
  restoreRevisionLabel: (rev: number) => `ревизию ${rev}`,
  versionLabel: (version: number) => `версию v${version}`,
  versionRevision: (rev: number) => `Ревизия ${rev}`,
  currentRevision: "Текущая",
  noRevisionMessage: "Без сообщения",
  noPublishedVersions: "Опубликованных версий пока нет.",
  restore: "Восстановить",
  restoring: "Восстановление…",
  restoreDialogAria: "Подтверждение восстановления",
  restoreDialogTitle: (target: string) => `Восстановить ${target}?`,
  restoreDiscardWarning: "Текущие несохранённые правки будут отброшены.",
  restoreBody: "Сервер создаст новую ревизию черновика из выбранного снимка.",
  restoreCancel: "Отменить",
  restoreConfirm: "Восстановить",
  leaveDialogAria: "Несохранённые правки",
  leaveTitle: "Уйти без сохранения?",
  leaveBody: "В черновике есть несохранённые правки — при уходе они будут потеряны.",
  leaveStay: "Остаться",
  leaveConfirm: "Уйти",
  copyLocalJson: "Скопировать локальный JSON",
  reloadDraft: "Перезагрузить черновик (правки будут потеряны)",
  // Диалог конфликта ревизий (W2-4)
  conflictDialogAria: "Конфликт версий черновика",
  conflictDialogTitle: (rev: number) => `Черновик изменён снаружи (rev ${rev})`,
  conflictBody: "Пока вы редактировали, черновик сохранил кто-то ещё. Сравните изменения и решите, что делать.",
  conflictTheirsTitle: "Изменено снаружи",
  conflictYoursTitle: "Ваши изменения",
  conflictNoChanges: "Структурных изменений не обнаружено.",
  conflictOverwrite: "Перезаписать",
  conflictOverwriteHint: "«Перезаписать» сохранит вашу версию поверх внешних изменений.",
  conflictCancel: "Отменить",
  conflictFetchFailed: "Не удалось загрузить актуальный черновик для сравнения",
  // Адреса структурного diff и 422-ошибок (W2-4)
  diffScreenLabel: (name: string) => `Экран «${name}»`,
  diffScreensLabel: "Экраны",
  diffDocLabel: "Документ",
  diffStateLabel: "Состояние",
  diffFlowLabel: (name: string) => `Сценарий «${name}»`,
  diffFlowStepsLabel: "шаги",
  diffDesignSystemLabel: "Дизайн-система",
  diffTypeLabel: "тип",
  diffHandlerLabel: (event: string) => `обработчик «${event}»`,
  diffRepeatLabel: "повтор (repeat)",
  diffSlotLabel: "слот",
  diffChildrenLabel: "дочерние элементы",
  diffVisibleLabel: "видимость",
  diffNoteLabel: "заметка",
  diffCanvasLabel: "холст",
  diffOverridesLabel: "состояние экрана",
  diffRootLabel: "корневой элемент",
  diffKindAdded: "добавлено",
  diffKindRemoved: "удалено",
  diffKindChanged: "изменено",
  diffKindRenamed: "переименовано",
  diffScalarDetail: (before: string, after: string) => `«${before}» → «${after}»`,
  canvasAria: "Холст редактора",
  screensStripAria: "Экраны прототипа",
  copyDialogAria: "Локальный JSON",
  copyDialogTitle: "Скопируйте локальный JSON вручную",
  copyUnavailable: "Автоматическое копирование недоступно.",
  clipboardUnavailable: "Clipboard API недоступен",
  close: "Закрыть",
  noContent: "Нет содержимого",
  selectScreenAria: (name: string) => `Выбрать экран «${name}»`,
  screensTitle: (count: number) => `Экраны (${count})`,
  collapseStrip: "Свернуть",
  expandStrip: "Развернуть",
  // Инспектор редактора
  inspectorAria: "Инспектор",
  sectionElement: "Элемент",
  sectionEvents: "События",
  sectionScreen: "Экран",
  sectionPrototype: "Прототип",
  screenMissing: "Экран не найден.",
  typeLabel: "Тип:",
  selectElementHint: "Выберите элемент на холсте или в дереве.",
  nameLabel: "Название",
  noteLabel: "Заметка",
  descriptionLabel: "Описание",
  startScreenLabel: "Стартовый экран",
  deviceLabel: "Устройство",
  canvasLegend: "Холст",
  widthLabel: "Ширина",
  heightLabel: "Высота",
  canvasWidthAria: "Ширина холста",
  canvasHeightAria: "Высота холста",
  canvasSizeError: "Укажите положительные ширину и высоту вместе",
  invalidJson: "Некорректный JSON",
  expectObject: "Ожидается JSON-объект",
  emptyScreen: "На экране пока нет элементов.",
  orphans: (count: number) => `Вне дерева (${count})`,
  expandElement: (type: string) => `Развернуть ${type}`,
  collapseElement: (type: string) => `Свернуть ${type}`,
  elementBreadcrumbsAria: "Предки элемента",
  screenBreadcrumb: "Экран",
  overridesDepthError: (limit: number) => `Глубина stateOverrides не должна превышать ${limit}`,
  forbiddenKeyError: (key: string) => `Ключ «${key}» запрещён`,
  // Форма пропов (W2-3)
  propNumberRequired: "Поле обязательное — укажите число",
  propNumberInvalid: "Введите число",
  propUnsetOption: "— не задано —",
  propRequiredEmptyWarning: "Обязательное поле пустое",
  assetUrlMode: "URL",
  assetMode: "Ассет",
  assetSelect: "Выберите ассет",
  assetUpload: "Загрузить…",
  assetUploadInput: "Загрузить ассет",
  assetUploading: "Загрузка…",
  assetUploadFailed: "Не удалось загрузить ассет",
  assetEmpty: "В этой ревизии пока нет ассетов",
  assetMeta: (mime: string, size: string) => `${mime} · ${size}`,
} as const;
