// Строки редактора прототипов (W0-5).

/** document.title редактора черновика (W0-3). */
export const editorDocumentTitle = (docName: string) => `${docName} · Редактор`;

export const editor = {
  dirtyAria: "Есть несохранённые изменения",
  saving: "Сохранение…",
  notSaved: "Не сохранено",
  saved: "Сохранено",
  save: "Сохранить",
  fixIssues: "Исправьте ошибки:",
  conflictTitle: (rev: number) => `Черновик изменён (rev ${rev})`,
  copyLocalJson: "Скопировать локальный JSON",
  reloadDraft: "Перезагрузить черновик (правки будут потеряны)",
  canvasAria: "Холст редактора",
  screensStripAria: "Экраны прототипа",
  copyDialogAria: "Локальный JSON",
  copyDialogTitle: "Скопируйте локальный JSON вручную",
  copyUnavailable: "Автоматическое копирование недоступно.",
  clipboardUnavailable: "Clipboard API недоступен",
  close: "Закрыть",
  noContent: "Нет содержимого",
  selectScreenAria: (name: string) => `Выбрать экран «${name}»`,
  screensTitle: (count: number) => `Экраны (${count})`,
  collapseStrip: "Свернуть",
  expandStrip: "Развернуть",
  // Инспектор редактора
  inspectorAria: "Инспектор",
  sectionElement: "Элемент",
  sectionScreen: "Экран",
  sectionPrototype: "Прототип",
  screenMissing: "Экран не найден.",
  typeLabel: "Тип:",
  selectElementHint: "Выберите элемент на холсте или в дереве.",
  nameLabel: "Название",
  noteLabel: "Заметка",
  descriptionLabel: "Описание",
  startScreenLabel: "Стартовый экран",
  deviceLabel: "Устройство",
  canvasLegend: "Холст",
  widthLabel: "Ширина",
  heightLabel: "Высота",
  canvasWidthAria: "Ширина холста",
  canvasHeightAria: "Высота холста",
  canvasSizeError: "Укажите положительные ширину и высоту вместе",
  invalidJson: "Некорректный JSON",
  expectObject: "Ожидается JSON-объект",
  emptyScreen: "На экране пока нет элементов.",
  orphans: (count: number) => `Вне дерева (${count})`,
  overridesDepthError: (limit: number) => `Глубина stateOverrides не должна превышать ${limit}`,
  forbiddenKeyError: (key: string) => `Ключ «${key}» запрещён`,
} as const;
