// Строки галереи прототипов (W0-5).

export const gallery = {
  kicker: "Галерея",
  title: "Прототипы",
  subtitle: "Выберите флоу, чтобы открыть его первый экран.",
  countLabel: (n: number) => `Всего прототипов: ${n}`,
  overflowActionsAria: "Действия",
  newPrototype: "Новый прототип",
  createDialogAria: "Создание прототипа",
  createDialogTitle: "Новый прототип",
  nameLabel: "Название прототипа",
  namePlaceholder: "Например, оформление заказа",
  systemLabelCreate: "Дизайн-система",
  create: "Создать прототип",
  creating: "Создаём…",
  cancel: "Отмена",
  createFailed: "Не удалось создать прототип. Попробуйте ещё раз.",
  hostStarterReady: "Стартовый экран использует только Image и Hotspot; компоненты можно добавить позже.",
  initialRevisionMessage: (version: number) => `Стартовый шаблон v${version}`,
  loading: "Загружаем прототипы…",
  apiUnavailable: "API недоступен",
  designSystemsAria: "Дизайн-системы",
  allSystems: "Все",
  tabsAria: "Разделы галереи",
  tabMine: "Мои",
  tabShared: "Общие",
  tabArchive: "Архив",
  tabService: "Служебные",
  // Lifecycle-виды прототипа (волна 0).
  kindsAria: "Виды прототипов",
  allKinds: "Все виды",
  kindLabel: "Вид",
  kindNames: {
    "product-flow": "Продуктовый флоу",
    "composition-fixture": "Фикстура композиции",
    "component-gallery": "Галерея компонентов",
    evidence: "Доказательство",
    "visual-reference": "Визуальный эталон",
    experiment: "Эксперимент",
  } as Record<string, string>,
  derivedFrom: (id: string) => `Производный от: ${id}`,
  derivedFromLabel: "Производный от",
  lifecycleAction: "Вид и теги…",
  lifecycleDialogTitle: "Вид и теги прототипа",
  lifecycleDialogAria: "Вид и теги прототипа",
  lifecycleTagsLabel: "Теги (через запятую)",
  lifecycleTagsHint: "Только латиница в нижнем регистре и дефисы, до 16 тегов.",
  lifecycleSave: "Сохранить",
  lifecycleSaving: "Сохраняем…",
  lifecycleFailed: "Не удалось сохранить вид и теги прототипа.",
  tagsLabel: "Теги",
  searchLabel: "Поиск по названию",
  searchPlaceholder: "Введите название прототипа",
  sortLabel: "Сортировка",
  sortUpdated: "Сначала обновлённые",
  sortName: "По названию",
  noDescription: "Без описания",
  deviceLabel: "Устройство",
  screensLabel: "Экраны",
  systemLabel: "Система",
  updatedLabel: "Обновлён",
  editorLink: "Редактор",
  ownerBadge: (name: string) => `Владелец: ${name}`,
  publish: "Опубликовать",
  unpublish: "Снять с публикации",
  archive: "В архив",
  restore: "Вернуть из архива",
  statusChanging: "Меняем статус…",
  statusChangeFailed: "Не удалось изменить статус прототипа.",
  // Диалог публикации с отчётом о готовности (волна 4, план 2026-07-27)
  publishDialogAria: "Публикация прототипа",
  publishDialogTitle: "Опубликовать прототип",
  publishDialogBody: "Прототип станет виден всем в разделе «Общие». Отчёт ниже показывает готовность головной ревизии.",
  publishConfirm: "Опубликовать",
  publishing: "Публикуем…",
  restoreNotRenderable: "Прототип нельзя вернуть из архива: текущая ревизия не отображается.",
  editorForbiddenNotice: "Редактировать этот прототип может только его владелец.",
  presentLink: "Презентация",
  qrOnPhone: "QR на телефон",
  shareDialogTitle: "QR на телефон",
  shareVersionsLoading: "Загружаем версии…",
  shareVersionsLoadFailed: "Не удалось загрузить версии для ссылки.",
  shareVersionsEmpty: "Опубликованных версий для ссылки нет.",
  versionsMenu: "Версии…",
  versionsMenuAria: (name: string) => `Опубликованные версии «${name}»`,
  versionsLoading: "Загружаем версии…",
  versionsLoadFailed: "Не удалось загрузить версии.",
  noVersions: "Опубликованных версий нет.",
  emptyFiltered: "В этом разделе нет прототипов с выбранными фильтрами.",
  emptySearch: "По вашему запросу ничего не найдено.",
  emptyTitle: "Создайте первый прототип",
  empty: "Выберите дизайн-систему — мы подготовим валидные стартовые экраны.",
  noUsableSystemsTitle: "Нужна дизайн-система с компонентами",
  noUsableSystemsBody: "Создайте дизайн-систему и опубликуйте хотя бы один компонент, чтобы начать новый прототип.",
  createDesignSystem: "Создать дизайн-систему",
  legacySystem: "Архивная система",
  // Экспорт/импорт бандлов (ZIP).
  exportGroupLabel: "Экспорт",
  exportDraft: "Экспорт черновика",
  exportVersionAction: (version: number) => `Экспорт v${version}`,
  exportLatest: "Экспорт",
  exporting: "Экспортируем…",
  exportError: "Не удалось экспортировать бандл.",
  exportAll: "Экспортировать всё",
  importButton: "Импортировать",
  importDialogAria: "Импорт бандла",
  importDialogTitle: "Импорт бандла",
  importIntro: "Выберите ZIP-бандл — мы сначала покажем предварительный отчёт, а импорт запустится только по вашей команде.",
  importChooseFile: "Выбрать файл…",
  importChangeFile: "Выбрать другой файл",
  importFileInputLabel: "ZIP-бандл для импорта",
  importChecking: "Проверяем бандл…",
  importApplying: "Импортируем…",
  importApply: "Импортировать",
  importDone: "Готово",
  importPreviewTitle: "Предварительный отчёт",
  importPreviewNote: "Предварительно — компиляция компонентов проверяется при импорте.",
  importResultTitle: "Отчёт об импорте",
  importPreviewFailedNote: "Предварительная проверка нашла ошибки. Импорт не запустится, пока они не будут исправлены.",
  importFailedNote: "Импорт завершился с ошибками — часть элементов не была записана.",
  importSummary: (created: number, reused: number, skipped: number, errors: number) => `Создано: ${created} · Переиспользовано: ${reused} · Пропущено: ${skipped} · Ошибок: ${errors}`,
  importError: "Не удалось обработать бандл.",
  importColType: "Тип",
  importColId: "Идентификатор",
  importColAction: "Результат",
  importColDetail: "Детали",
  importItemTypes: { asset: "Ассет", designSystem: "Дизайн-система", component: "Компонент", composition: "Композиция", prototype: "Прототип" },
  importActions: { created: "создан", reused: "переиспользован", skipped: "пропущен", error: "ошибка" },
  importRemappedTo: (id: string) => `новый id: ${id}`,
} as const;

export { deviceNames } from "./common";

export const versionLink = (version: number) => `Версия v${version}`;
export const cjmVersionLink = (version: number) => `CJM v${version}`;
