// Строки галереи прототипов (W0-5).

export const gallery = {
  title: "Прототипы",
  subtitle: "Выберите флоу, чтобы открыть его первый экран.",
  newPrototype: "Новый прототип",
  createDialogAria: "Создание прототипа",
  createDialogTitle: "Новый прототип",
  nameLabel: "Название прототипа",
  namePlaceholder: "Например, оформление заказа",
  systemLabelCreate: "Дизайн-система",
  create: "Создать прототип",
  creating: "Создаём…",
  cancel: "Отмена",
  createFailed: "Не удалось создать прототип. Попробуйте ещё раз.",
  customStarterLoading: "Проверяем стартовый компонент дизайн-системы…",
  customStarterUnavailable: "Каталог компонентов недоступен: нельзя проверить валидный стартовый экран.",
  customStarterMissing: "Создание недоступно: в этой дизайн-системе нет опубликованного компонента с валидным example для стартового экрана.",
  customStarterReady: (componentName: string) => `Стартовый экран будет создан с компонентом ${componentName}.`,
  builtinStarterReady: "Будут созданы два стартовых экрана с базовым переходом.",
  initialRevisionMessage: (version: number) => `Стартовый шаблон v${version}`,
  loading: "Загружаем прототипы…",
  apiUnavailable: "API недоступен",
  designSystemsAria: "Дизайн-системы",
  allSystems: "Все",
  searchLabel: "Поиск по названию",
  searchPlaceholder: "Введите название прототипа",
  sortLabel: "Сортировка",
  sortUpdated: "Сначала обновлённые",
  sortName: "По названию",
  noDescription: "Без описания",
  deviceLabel: "Устройство",
  screensLabel: "Экраны",
  systemLabel: "Система",
  updatedLabel: "Обновлён",
  editorLink: "Редактор",
  presentLink: "Презентация",
  versionsMenu: "Версии…",
  versionsMenuAria: (name: string) => `Опубликованные версии «${name}»`,
  versionsLoading: "Загружаем версии…",
  versionsLoadFailed: "Не удалось загрузить версии.",
  noVersions: "Опубликованных версий нет.",
  emptyFiltered: "Нет прототипов с выбранной дизайн-системой.",
  emptySearch: "По вашему запросу ничего не найдено.",
  emptyTitle: "Создайте первый прототип",
  empty: "Выберите дизайн-систему — мы подготовим валидные стартовые экраны.",
} as const;

export { deviceNames } from "./common";

export const versionLink = (version: number) => `Версия v${version}`;
export const cjmVersionLink = (version: number) => `CJM v${version}`;
