// Generated by scripts/generate-sdk.ts. Do not edit by hand.
// Regenerate: npm run generate:sdk -- --design-system <id> [--api <base> | --from <snapshot.json>]
// Design system: sdk-demo · components: 4

/** Render-time directive accepted in place of a literal prop value ($state/$bindState/$template/$cond/$asset). */
export type Directive = { [key: `$${string}`]: unknown };
/** An authored prop value: a literal, or a directive resolved by the runtime. */
export type Authored<T> = T | Directive;

/** Pinned footer with a primary action and optional secondary links. */
export interface DemoActionFooterProps {
  disabled?: Authored<boolean>;
  links?: Authored<Array<{
    id: string;
    label: string;
  }>>;
  primaryLabel: Authored<string>;
}
export type DemoActionFooterSlots = never;
export type DemoActionFooterEvents = "press" | "secondaryPress";
export interface DemoActionFooterEventPayloads {
  press: {
    itemId: string;
  };
  secondaryPress: Record<string, never>;
}

/** Small status badge. */
export interface DemoBadgeProps {
  count?: Authored<number | string>;
  meta?: Authored<{
    [key: string]: string;
  }>;
  origin?: Authored<[number, number]>;
  text: Authored<string>;
}
export type DemoBadgeSlots = never;
export type DemoBadgeEvents = never;
export type DemoBadgeEventPayloads = Record<string, never>;

/** Source-exact navigation bar with a title and an optional back affordance. */
export interface DemoNavBarProps {
  logoUrl?: Authored<string>;
  showBack?: Authored<boolean>;
  title: Authored<string>;
  tone: Authored<"light" | "dark">;
}
export type DemoNavBarSlots = never;
export type DemoNavBarEvents = never;
export type DemoNavBarEventPayloads = Record<string, never>;

/** Named-slot shell: header, content and footer regions of a screen. */
export interface DemoScreenShellProps {
  background?: Authored<"surface" | "elevated">;
}
export type DemoScreenShellSlots = "content" | "footer" | "header";
export type DemoScreenShellEvents = never;
export type DemoScreenShellEventPayloads = Record<string, never>;

export interface CatalogComponents {
  DemoActionFooter: {
    id: "demo-action-footer";
    version: 3;
    props: DemoActionFooterProps;
    slots: DemoActionFooterSlots;
    events: DemoActionFooterEvents;
    eventPayloads: DemoActionFooterEventPayloads;
    atomicLevel: "molecule";
    namedSlots: false;
    typedEvents: true;
    scope: undefined;
    canonicalFor: never;
  };
  DemoBadge: {
    id: "demo-badge";
    version: 1;
    props: DemoBadgeProps;
    slots: DemoBadgeSlots;
    events: DemoBadgeEvents;
    eventPayloads: DemoBadgeEventPayloads;
    atomicLevel: "atom";
    namedSlots: false;
    typedEvents: false;
    scope: undefined;
    canonicalFor: never;
  };
  DemoNavBar: {
    id: "demo-nav-bar";
    version: 2;
    props: DemoNavBarProps;
    slots: DemoNavBarSlots;
    events: DemoNavBarEvents;
    eventPayloads: DemoNavBarEventPayloads;
    atomicLevel: "organism";
    namedSlots: false;
    typedEvents: false;
    scope: undefined;
    canonicalFor: never;
  };
  DemoScreenShell: {
    id: "demo-screen-shell";
    version: 1;
    props: DemoScreenShellProps;
    slots: DemoScreenShellSlots;
    events: DemoScreenShellEvents;
    eventPayloads: DemoScreenShellEventPayloads;
    atomicLevel: "template";
    namedSlots: true;
    typedEvents: false;
    scope: undefined;
    canonicalFor: never;
  };
}

export type ComponentName = keyof CatalogComponents & string;

export type PropsOf<N extends ComponentName> = CatalogComponents[N]["props"];

export type SlotsOf<N extends ComponentName> = CatalogComponents[N]["slots"];

export type EventsOf<N extends ComponentName> = CatalogComponents[N]["events"];

export type EventPayloadsOf<N extends ComponentName> = CatalogComponents[N]["eventPayloads"];
